### ISSUE TITLE
OWIN Authentication issue while hitting some pages in Web Application

### ISSUE THREAD

**Issue by bharatmangal04** [owin/owin#53]
OWIN Pipeline throwing exception 

   at Microsoft.IdentityModel.Protocols.AuthenticationProtocolMessage.SetParameter(String parameter, String value)
   at Microsoft.IdentityModel.Protocols.WsFederationMessage..ctor(IEnumerable`1 parameters)
   at Microsoft.Owin.Security.WsFederation.WsFederationAuthenticationHandler.<AuthenticateCoreAsync>d__1f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by Tratcher** [comment]
This can be closed as a duplicate of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/143

**Comment by bharatmangal04** [comment]
This is not related to Azure AD. Also Above mentioned issue related to OAuth. So we need to keep this open to find out the resolution. 

Do let me know if need more information from my side.

**Comment by Tratcher** [comment]
AzureAd owns Microsoft.IdentityModel.Protocols.WsFederationMessage

**Comment by Tratcher** [comment]
Alternatively move it to http://katanaproject.codeplex.com/ for Microsoft.Owin.Security.WsFederation

**Comment by bharatmangal04** [comment]
Thanks.. Posted issue on Katana. Also provided issue above for AzureAd. I did not see the resolution for this.

**Comment by bharatmangal04** [comment]
Closing issue as already raised with Azure AD

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/495
